config/routes.rb
Rails.application.routes.draw do

  root 'screens#index'

  resources :screens
  get 'slideshows' => 'slideshows#index'

end

app/models/screen.rb
class Screen < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/screens_controller.rb
class ScreensController < ApplicationController

	def index
		@screens = Screen.all
	end

	def slideshow
		@screens = Screen.all
	end

	def new
		@screen = Screen.new
	end

	def show
		@screen = Screen.find(params[:id])
	end

	def edit
		@screen = Screen.find(params[:id])
	end

	def update
		@screen = Screen.find(params[:id])
		if @screen.update(params[:screen].permit(:title, :text))
			broadcast("/screens", @screen, "edit")
			redirect_to @screen
		else
			render 'edit'
		end
	end

	def create
		#render text: params[:screen].inspect
		@screen = Screen.new(params[:screen].permit(:title, :text))
		if @screen.save
			#broadcast("/screens/#{@screen}", @screen)
			broadcast("/screens", @screen, "create")
			redirect_to @screen
		else
			render 'new'
		end
	end

	def destroy
		@screen = Screen.find(params[:id])
		@screen.destroy
		broadcast("/screens", @screen, "destroy")
		redirect_to screens_path
	end

  private

    def broadcast(channel, object, type)
      screen = {:channel => channel, :data => {:object => object, :channel => channel, :type => type}, :ext => {:auth_token => FAYE_TOKEN}}
      uri = URI.parse("http://localhost:9292/faye")
      Net::HTTP.post_form(uri, :message => screen.to_json)
    end

end

app/controllers/slideshows_controller.rb
class SlideshowsController < ApplicationController

	def index
		@screens = Screen.all
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/screens_helper.rb
module ScreensHelper
end

app/helpers/slideshows_helper.rb
module SlideshowsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Monitors Centralized Management</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "http://localhost:9292/faye.js" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/screens/_form.html.erb
<%= form_for @screen do |f| %>
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/screens/edit.html.erb
<h1>Edit screen</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', screens_path %>

app/views/screens/index.html.erb
<h1>Screens</h1>

<table id="screens">
  <tr>
    <th>Text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @screens.each do |screen| %>
	<tr id="screen_<%= screen.id %>">
		<td><%= screen.text %></td>
		<td><%= link_to 'Show', screen %></td>
		<td><%= link_to 'Edit', edit_screen_path(screen) %></td>
		<td><%= link_to 'Destroy', screen_path(screen),
		method: :delete, data: { confirm: 'Are you sure?' } %></td>
	</tr>
<% end %>

</table>

<%= link_to 'New screen', new_screen_path %>

app/views/screens/new.html.erb
<h1>New screen</h1>

<%= render 'form' %>

<%= link_to 'Back', screens_path %>

app/views/screens/show.html.erb
<p>
  <strong>Text:</strong>
  <%= @screen.text %>
</p>

<%= link_to 'Edit Screen', edit_screen_path(@screen) %> |
<%= link_to 'Back', screens_path %>

app/views/slideshows/index.html.erb
<h1>Slideshows</h1>

<div id="screens">

	<% @screens.each do |screen| %>
			<span id="screen_<%= screen.id %>"><%= screen.text %></span><br />
	<% end %>

</div>

<script type="text/javascript">
	faye = new Faye.Client('http://localhost:9292/faye');
	faye.subscribe("/screens", function (data) {
		console.log(data);
		if (data.type == "create") {
			$("#screens").append("<span id=\"screen_"+ data.object.id +"\">"+ data.object.text +"</span>")
		} else if (data.type == "edit") {
			$("#screen_"+data.object.id).html(data.object.text)
		} else if (data.type == "destroy") {
			$("#screen_"+data.object.id).remove()
		}
	});
</script>